replicaCount: 2

image:
  repository: minabisa90/eks-helm-flask-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
